    FROM quay.io/acb-fr/qiot-sensor-service-base:1.0.0

    LABEL app="QIoT project"
    LABEL maintener="David AUFFRAY <david.auffray@axians.com>"
    LABEL major_version="1"
    LABEL minor_version="7"

    WORKDIR /usr/src/app

    COPY requirements.txt ./

    ENV REDIS_HOST "redis"
    ENV REDIS_PORT 6379
    ENV REDIS_DB 0

    RUN pip install --no-cache-dir -r requirements.txt

    COPY . .

    CMD [ "python3", "qiot_to_redis.py"]
